plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.manager.assistant'
    compileSdkVersion 37

    defaultConfig {
        applicationId "com.manager.assitant"
        minSdk 26
        //noinspection OldTargetApi
        targetSdk 36
        versionCode 58
        versionName "1.8.14"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material.v1130
    implementation libs.recyclerview
    implementation libs.constraintlayout
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.activity
    implementation libs.materialdatetimepicker
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation libs.jackson.databind
    implementation libs.viewpager2
    implementation libs.core
    implementation libs.rxandroid
    implementation libs.rxjava
    implementation libs.swiperefreshlayout
    implementation libs.documentfile
    implementation libs.work.runtime
    implementation libs.camera.core
    implementation libs.camera.camera2
    implementation libs.camera.lifecycle
    implementation libs.camera.view
    implementation libs.glide
    implementation libs.photoview
    implementation libs.dynamicanimation
    implementation libs.flexbox
}